name: Server-Manager
version: '${project.version}'
main: org.bliffbot.servermanager.Server_Manager
load: STARTUP
authors: [Bliffbot]
description: A Minecraft Plugin for Spigot server that allows you to manage various things.
